version: '3.8'

services:
  # Combined frontend/backend service using our integrated app
  integrated_app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./frontend:/app/frontend
      - ./uploads:/app/static/uploads
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/summarease
      - REDIS_URL=redis://redis:6379/0
      - PROCESS_DIRECTLY=True
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_REGION=us-east-1
      - S3_BUCKET_NAME=
    command: uvicorn integrated_app:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - redis
      - db

  # Alternatively, you can use separate frontend and backend services
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/summarease
      - REDIS_URL=redis://redis:6379/0
      - PROCESS_DIRECTLY=True
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_REGION=us-east-1
      - S3_BUCKET_NAME=
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - redis
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - api

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=summarease
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/summarease
      - REDIS_URL=redis://redis:6379/0
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_REGION=us-east-1
      - S3_BUCKET_NAME=
    command: celery -A celery_worker.celery worker --loglevel=info
    depends_on:
      - redis
      - db

  flower:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "5555:5555"
    command: celery -A celery_worker.celery flower --port=5555
    depends_on:
      - redis
      - celery_worker

volumes:
  postgres_data:
  redis_data: